### ISSUE TITLE
Use value tuples with explicitly named fields

### ISSUE THREAD

**Issue by blair-ahlquist** [TileDB-Inc/TileDB-CSharp#232]
Value tuples have the advantage in that they are self-documenting. For example, in [this](https://github.com/TileDB-Inc/TileDB-CSharp/blob/5686783b68a88c9bf2a9de1ecfaa5644965d7f6a/sources/TileDB.CSharp/Query.cs#L599) method, the return type could be `(T start, T end, T stride)`.

**Comment by teo-tsirpanis** [comment]
Hello @blair-ahlquist, you are looking at a pretty old version of the library. Since then these APIs have been deprecated and replaced with APIs on the [`Subarray`](https://github.com/TileDB-Inc/TileDB-CSharp/blob/956fe550d3e73d4371b7eb301cf752976035d94c/sources/TileDB.CSharp/Subarray.cs) class that do return value tuples.

If you have existing code using these methods, [this document](https://github.com/TileDB-Inc/TileDB-CSharp/blob/main/docs/obsoletions.md#tiledb0011) will help you migrate to the new ones.

Let me know if you have any more questions.
